DNE.Web/Controllers/CategoryController.cs
using DNE.Data.Models;
using DNE.Repository.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DNE.Web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly UserManager<IdentityUser> _userManager;

        public CategoryController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            this.context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View(context.Categories.ToList());
        }

        public async Task<IActionResult> Create()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            var userId = user.Id;

            Category category = new Category()
            {
                CreatedByUserId = userId,
                UpdatedByUserId = userId,
                DateCreated = DateTime.Now,
                DateUpdated = DateTime.Now
            };

            return View(category);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Category Category)
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            var userId = user.Id;

            if (ModelState.IsValid)
            {
                await context.Categories.AddAsync(Category);
                await context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            Category category = new Category()
            {
                CreatedByUserId = userId,
                UpdatedByUserId = userId,
                DateCreated = DateTime.Now,
                DateUpdated = DateTime.Now
            };

            return View(category);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            var findById = await context.Categories.FindAsync(id);

            Category category = new Category()
            {
                Name = findById.Name,
                CreatedByUserId = findById.CreatedByUserId,
                UpdatedByUserId = findById.UpdatedByUserId,
                DateCreated= findById.DateCreated,
                DateUpdated= findById.DateUpdated,
            };
            
            return View(category);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Category category, int id)
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            var userId = user.Id;
            var findById = await context.Categories.FindAsync(id);

            if (ModelState.IsValid)
            {
                findById.Name = category.Name;
                findById.UpdatedByUserId = category.UpdatedByUserId;
                findById.DateUpdated = category.DateUpdated;
                
                await context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            Category categoryDomainModel = new Category()
            {
                Name = findById.Name,
                CreatedByUserId = findById.CreatedByUserId,
                UpdatedByUserId = findById.UpdatedByUserId,
                DateCreated = findById.DateCreated,
                DateUpdated = findById.DateUpdated,
            };

            return View(categoryDomainModel);
        }

        public async Task<IActionResult> Delete(int id)
        {
            
            var findById = await context.Categories.FindAsync(id);

            Category categoryDomainModel = new Category()
            {
                Name = findById.Name,
                CreatedByUserId = findById.CreatedByUserId,
                UpdatedByUserId = findById.UpdatedByUserId,
                DateCreated = findById.DateCreated,
                DateUpdated = findById.DateUpdated,
            };

            return View(categoryDomainModel);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Category category, int id)
        {
            
            var findById = await context.Categories.FindAsync(id);

            if (ModelState.IsValid)
            {
                context.Categories.Remove(findById);
                await context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            

            return View();
        }
    }
}

DNE.Web/Controllers/LeadController.cs
using DNE.Data.Models;
using DNE.Data.ViewModels;
using DNE.Repository.Data;
using DNE.Repository.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DNE.Web.Controllers
{
    public class LeadController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly UserManager<IdentityUser> _userManager;

        public LeadController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            this.context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            //var leads = ilead.ToListLeads();
            var leads = context.Leads.Include(m => m.Category).ToList();
            return View(leads);
        }

        public async Task<IActionResult> Create()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            var userId = user.Id;

            Lead lead = new Lead()
            {
                CreatedByUserId = userId,
                UpdatedByUserId = userId,
                DateCreated = DateTime.Now,
                DateUpdated = DateTime.Now
            };

            CategoryLeadViewModel categoryLeadViewModel = new CategoryLeadViewModel()
            {
                Lead = lead,
                Categories = await context.Categories.ToListAsync()
            };

            return View(categoryLeadViewModel);
        }

        [HttpPost, ValidateAntiForgeryToken, ActionName("Create")]
        public async Task<IActionResult> Create(Lead lead)
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            var userId = user.Id;

            Lead leadDomainModel = new Lead()
            {
                CreatedByUserId = userId,
                UpdatedByUserId = userId,
                DateCreated = DateTime.Now,
                DateUpdated = DateTime.Now
            };

            CategoryLeadViewModel categoryLeadViewModel = new CategoryLeadViewModel()
            {
                Lead = leadDomainModel,
                Categories = await context.Categories.ToListAsync()
            };
            if (ModelState.IsValid)
            {
                await context.Leads.AddAsync(lead);
                await context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(categoryLeadViewModel);
        }
    }
}

DNE.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DNELayer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DNE.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">DNELayer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Item Menu</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item" asp-controller="Category" asp-action="Index">Category</a>
                                    <a class="dropdown-item" asp-controller="Lead" asp-action="Index">Lead</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - DNE.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="https://kit.fontawesome.com/49cbe8ebac.js" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DNE.Web/Views/Shared/_categoryIndexTable.cshtml
@model IEnumerable<Category>

@if (Model.Count() > 0)
    {
        <div class="mt-2">
            <table id="" class="table table-hover table-bordered text-center" style="background-color:lightskyblue" width="100%">
                    <thead class="table table-primary">
                        <tr>
                            <th>@Html.DisplayNameFor(m => m.Id)</th>
                            <th>@Html.DisplayNameFor(m => m.Name)</th>
                            <th>@Html.DisplayNameFor(m => m.CreatedByUserId)</th>
                            <th>@Html.DisplayNameFor(m => m.UpdatedByUserId)</th>
                            <th>@Html.DisplayNameFor(m => m.DateCreated)</th>
                            <th>@Html.DisplayNameFor(m => m.DateUpdated)</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var items in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(m => items.Id)</td>
                                <td>@Html.DisplayFor(m => items.Name)</td>
                                <td>@Html.DisplayFor(m => items.CreatedByUserId)</td>
                                <td>@Html.DisplayFor(m => items.UpdatedByUserId)</td>
                                <td>@Html.DisplayFor(m => items.DateCreated)</td>
                                <td>@Html.DisplayFor(m => items.DateUpdated)</td>
                                <td>
                                    <a asp-controller="Category" asp-action="Edit" asp-route-id="@items.Id"  class="btn btn-dark text-white btn-sm"><i class="fas fa-edit"></i> &nbsp; Edit</a>
                                    <a class="btn btn-danger text-white btn-sm" asp-action="Delete" asp-controller="Category" asp-route-id="@items.Id"><i class="fas fa-trash-alt"></i> &nbsp; Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
            </table>
        </div>
    }
    else
    {
        <br />
        <div class="alert alert-danger text-danger" role="alert">No categories available right now !</div> 
    }
</div>

DNE.Web/Views/Shared/_leadIndexTable.cshtml
@model IEnumerable<Lead>

@if (Model.Count() > 0)
    {
        <div class="mt-2">
            <table id="" class="table table-hover table-bordered text-center" style="background-color:lightskyblue" width="100%">
                    <thead class="table table-primary">
                        <tr>
                            <th>@Html.DisplayNameFor(m => m.Id)</th>
                            <th>@Html.DisplayNameFor(m => m.FirstName)</th>
                            <th>@Html.DisplayNameFor(m => m.LastName)</th>
                            <th>@Html.DisplayNameFor(m => m.Email)</th>
                            <th>@Html.DisplayNameFor(m => m.Phone)</th>
                            <th>@Html.DisplayNameFor(m => m.CategoryId)</th>
                            <th>@Html.DisplayNameFor(m => m.CreatedByUserId)</th>
                            <th>@Html.DisplayNameFor(m => m.UpdatedByUserId)</th>
                            <th>@Html.DisplayNameFor(m => m.DateCreated)</th>
                            <th>@Html.DisplayNameFor(m => m.DateUpdated)</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var items in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(m => items.Id)</td>
                                <td>@Html.DisplayFor(m => items.FirstName)</td>
                                <td>@Html.DisplayFor(m => items.LastName)</td>
                                <td>@Html.DisplayFor(m => items.Email)</td>
                                <td>@Html.DisplayFor(m => items.Phone)</td>
                                <td>@Html.DisplayFor(m => items.Category.Name)</td>
                                <td>@Html.DisplayFor(m => items.CreatedByUserId)</td>
                                <td>@Html.DisplayFor(m => items.UpdatedByUserId)</td>
                                <td>@Html.DisplayFor(m => items.DateCreated)</td>
                                <td>@Html.DisplayFor(m => items.DateUpdated)</td>
                                <td>
                                    <a asp-controller="Lead" asp-action="Edit" asp-route-id="@items.Id"  class="btn btn-dark text-white btn-sm"><i class="fas fa-edit"></i> &nbsp; Edit</a>
                                    <a class="btn btn-danger text-white btn-sm" asp-action="Delete" asp-controller="Lead" asp-route-id="@items.Id"><i class="fas fa-trash-alt"></i> &nbsp; Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
            </table>
        </div>
    }
    else
    {
        <br />
        <div class="alert alert-danger text-danger" role="alert">No leads available right now !</div> 
    }
</div>